### ISSUE TITLE
Docs missing critical run local details

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/jekyll-theme-dnn-community#33]
The docs page assumes that there are some prerequisites already installed on a local computer.  

https://dnncommunity.github.io/jekyll-theme-dnn-community/

You'll be unable to successfully run `bundle exec jekyll serve` without first installing `Ruby` and `Bundle`.  

The doc should be updated to include a side note or something that helps people know what the missing step(s) actually is/are.

**Comment by david-poindexter** [comment]
## Just a few notes
* For Windows users, I highly recommend [RubyInstaller](https://rubyinstaller.org/)
* Then you'll want [RubyGems](https://rubygems.org/), which is a package management system for Ruby (think `npm` and `yarn` but for Ruby instead of `Node`).
* Lastly, you may find [Bundler](https://bundler.io/) handy for managing Ruby application's gems.

**Comment by david-poindexter** [comment]
Really the high-level instructions are covered in the README of this project.  The problem is that info is not included in the [Overview](https://dnncommunity.github.io/jekyll-theme-dnn-community/index.html) on the GitHub pages documentation for this repo.

**Comment by WillStrohl** [comment]
> ## Just a few notes
> * For Windows users, I highly recommend [RubyInstaller](https://rubyinstaller.org/)
> * Then you'll want [RubyGems](https://rubygems.org/), which is a package management system for Ruby (think `npm` and `yarn` but for Ruby instead of `Node`).
> * Lastly, you may find [Bundler](https://bundler.io/) handy for managing Ruby application's gems.

These notes appear to be missing from the PR.  Do we think they should be added to the documentation page?

**Comment by david-poindexter** [comment]
@hismightiness I realized after the fact that it is really all there on the [Jekyll installation](https://jekyllrb.com/docs/) page.  I just hate that there are so many layers and offshoot requirements to get it all working.  So it is a bit of a conundrum.  Do we re-invent the Jekyll documentation?  It is quite convoluted and complex.  I tend to lean on the point that it is beyond the scope of this project.

**Comment by WillStrohl** [comment]
Gotcha!  👍🏽
